#- name: Create AWS instance
#  hosts: 127.0.0.1
#  connection: local
#  gather_facts: False
#  remote_user: ubuntu
#  roles:
#     - createEc2Instnace
      
- name: copy code to AWS instance
  hosts: webserver
  #connection: local
  gather_facts: False
  remote_user: ubuntu
  roles:
    - setupAppServer
      