version : '2'

services:


    
#    depends_on:
#      - mongodb


  mongodb:
    build:
      context: .
      dockerfile: mongodbdocker
    image: webdb:tag
    ports:
      - 27017:27017

  nodejs:
    build:
      context: .
      dockerfile: nodejsdocker
    image: webapp:tag
    ports:
      - 80:80
    links:
      - mongodb