version : '2'

services:

  nodejs:
    build:
      context: .
      dockerfile: nodejsdocker
    image: webapp:tag
    ports:
      - 80:80
    
#    depends_on:
#      - mongodb
    links:
      - mongodb

  mongodb:
    build:
      context: .
      dockerfile: mongodbdocker
    image: webdb:tag
    ports:
      - 27017:27017