- name: copy code to ec2 instance
  debug:
    var: app_code
- name: install python
  raw: 'sudo apt-get -y install python'

- name: configure node
  shell: |
    sudo apt update -y
    sudo apt  install docker.io -y
    sudo apt  install docker-compose -y
    sudo usermod -aG docker ubuntu
    sudo service docker start
    sudo apt install git -y
    git clone https://github.com/nitishvu/MeanStackDockerAwsApp.git
    cd ~/MeanStackDockerAwsApp/app
    docker-compose up --build -d      
    exit 0



  